# Assignment Two — 2025

## Data Preprocessing
- Simple statistical evaluation of the data set;
- Identify the target variable(s);
- Identify if this is a regression or a classification task;
- Are there any missing data? What can you do about them?
- Which variables are relevant or irrelevant to the task?
- What type of validation/cross-validation procedure will you use? 
- Data visualisation.

In [102]:
# Install Package 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl

In [ ]:
# Loading the data
data = pd.read_csv("Euro_6_latest.csv", 
                   encoding= 'latin1') # encoding = 'latin1' is required because in the dataset, 
                                       # there are special characters. Latin1 is an encoding for Western Europe. 
data.head()
# From the data.head() code, we see that there are 45 columns. However, in this dataset, the last column is 'unnamed:44' and there is no values in this column. 
# This is because the last column in the original dataset is 'Date of change' with a comma, thus, the pandas see it as a column and include it. Thus, this last column should be slided out.
# Moreover, from the initial assessment, as the topic focuses on the car and emission, 'Noise Level dB (A)' is not relevant and it should be also dropped. 
# Similarly, 'Date of Change' column appears simply as an updated date of each row. Hence, it is dropped.

,Manufacturer,Model,Description,Transmission,Manual or Automatic,Engine Capacity,Fuel Type,Powertrain,Engine Power (PS),Engine Power (Kw),...,Emissions CO [mg/km],THC Emissions [mg/km],Emissions NOx [mg/km],THC + NOx Emissions [mg/km],Particulates [No.] [mg/km],RDE NOx Urban,RDE NOx Combined,Noise Level dB(A),Date of change,Unnamed: 44
0,ABARTH,500e MY23/24,114kW Electric (VL),A1,Electric - Not Applicable,0.0,Electricity,Battery Electric Vehicle (BEV) / Pure Electric...,155.0,114.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,68.0,17 October 2024,NaN
1,ABARTH,500e MY23/24,114kW Electric (VH),A1,Electric - Not Applicable,0.0,Electricity,Battery Electric Vehicle (BEV) / Pure Electric...,155.0,114.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,68.0,17 October 2024,NaN
2,ABARTH,500e MY23/24,114kW Electric Convertible (VL),A1,Electric - Not Applicable,0.0,Electricity,Battery Electric Vehicle (BEV) / Pure Electric...,155.0,114.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,68.0,17 October 2024,NaN
3,ABARTH,500e MY23/24,114kW Electric Convertible (VH),A1,Electric - Not Applicable,0.0,Electricity,Battery Electric Vehicle (BEV) / Pure Electric...,155.0,114.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,68.0,17 October 2024,NaN
4,ABARTH,595 MY23,Turismo 1.4 Tjet 165 hp Manual (VL),M5,Manual,1368.0,Petrol,Internal Combustion Engine (ICE),165.0,121.0,...,688.0,66.0,28.0,NaN,NaN,60.0,60.0,69.0,17 October 2024,NaN

In [104]:
data.shape

(3702, 45)

In [105]:
data.dtypes
# only data type for column 'Date of change' is not at the right match while the rest is correct.

Manufacturer                              object
Model                                     object
Description                               object
Transmission                              object
Manual or Automatic                       object
Engine Capacity                          float64
Fuel Type                                 object
Powertrain                                object
Engine Power (PS)                        float64
Engine Power (Kw)                        float64
Electric energy consumption Miles/kWh    float64
wh/km                                    float64
Maximum range (Km)                       float64
Maximum range (Miles)                    float64
Euro Standard                             object
Diesel VED Supplement                       bool
Testing Scheme                            object
WLTP Imperial Low                        float64
WLTP Imperial Medium                     float64
WLTP Imperial High                       float64
WLTP Imperial Extra High                 float64
WLTP Imperial Combined                   float64
WLTP Imperial Combined (Weighted)        float64
WLTP Metric Low                          float64
WLTP Metric Medium                       float64
WLTP Metric High                         float64
WLTP Metric Extra High                   float64
WLTP Metric Combined                     float64
WLTP Metric Combined (Weighted)          float64
WLTP CO2                                   int64
WLTP CO2 Weighted                        float64
Equivalent All Electric Range Miles      float64
Equivalent All Electric Range KM         float64
Electric Range City Miles                float64
Electric Range City Km                   float64
Emissions CO [mg/km]                     float64
THC Emissions [mg/km]                    float64
Emissions NOx [mg/km]                    float64
THC + NOx Emissions [mg/km]              float64
Particulates [No.] [mg/km]               float64
RDE NOx Urban                            float64
RDE NOx Combined                         float64
Noise Level dB(A)                        float64
Date of change                            object
Unnamed: 44                              float64
dtype: object

In [ ]:
# Drop 3 the last 3 columns
data = data.drop(columns=["Unnamed: 44", "Date of change", "Noise Level dB(A)"], axis = 1)
data.head()

,Manufacturer,Model,Description,Transmission,Manual or Automatic,Engine Capacity,Fuel Type,Powertrain,Engine Power (PS),Engine Power (Kw),...,Equivalent All Electric Range KM,Electric Range City Miles,Electric Range City Km,Emissions CO [mg/km],THC Emissions [mg/km],Emissions NOx [mg/km],THC + NOx Emissions [mg/km],Particulates [No.] [mg/km],RDE NOx Urban,RDE NOx Combined
0,ABARTH,500e MY23/24,114kW Electric (VL),A1,Electric - Not Applicable,0.0,Electricity,Battery Electric Vehicle (BEV) / Pure Electric...,155.0,114.0,...,NaN,223.0,359.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,ABARTH,500e MY23/24,114kW Electric (VH),A1,Electric - Not Applicable,0.0,Electricity,Battery Electric Vehicle (BEV) / Pure Electric...,155.0,114.0,...,NaN,205.0,330.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,ABARTH,500e MY23/24,114kW Electric Convertible (VL),A1,Electric - Not Applicable,0.0,Electricity,Battery Electric Vehicle (BEV) / Pure Electric...,155.0,114.0,...,NaN,223.0,359.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,ABARTH,500e MY23/24,114kW Electric Convertible (VH),A1,Electric - Not Applicable,0.0,Electricity,Battery Electric Vehicle (BEV) / Pure Electric...,155.0,114.0,...,NaN,205.0,330.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,ABARTH,595 MY23,Turismo 1.4 Tjet 165 hp Manual (VL),M5,Manual,1368.0,Petrol,Internal Combustion Engine (ICE),165.0,121.0,...,NaN,NaN,NaN,688.0,66.0,28.0,NaN,NaN,60.0,60.0

In [107]:
# check the datatype after the 'Date of change' data type is modified.
print(data.dtypes)

Manufacturer                              object
Model                                     object
Description                               object
Transmission                              object
Manual or Automatic                       object
Engine Capacity                          float64
Fuel Type                                 object
Powertrain                                object
Engine Power (PS)                        float64
Engine Power (Kw)                        float64
Electric energy consumption Miles/kWh    float64
wh/km                                    float64
Maximum range (Km)                       float64
Maximum range (Miles)                    float64
Euro Standard                             object
Diesel VED Supplement                       bool
Testing Scheme                            object
WLTP Imperial Low                        float64
WLTP Imperial Medium                     float64
WLTP Imperial High                       float64
WLTP Imperial Extra High                 float64
WLTP Imperial Combined                   float64
WLTP Imperial Combined (Weighted)        float64
WLTP Metric Low                          float64
WLTP Metric Medium                       float64
WLTP Metric High                         float64
WLTP Metric Extra High                   float64
WLTP Metric Combined                     float64
WLTP Metric Combined (Weighted)          float64
WLTP CO2                                   int64
WLTP CO2 Weighted                        float64
Equivalent All Electric Range Miles      float64
Equivalent All Electric Range KM         float64
Electric Range City Miles                float64
Electric Range City Km                   float64
Emissions CO [mg/km]                     float64
THC Emissions [mg/km]                    float64
Emissions NOx [mg/km]                    float64
THC + NOx Emissions [mg/km]              float64
Particulates [No.] [mg/km]               float64
RDE NOx Urban                            float64
RDE NOx Combined                         float64
dtype: object

In [108]:
pd.des

AttributeError: module 'pandas' has no attribute 'des'